### PR TITLE
Fix and Feature dump

### LINKED ISSUE #317: Bug: Original filename isn't saved in UTF-8
### What happened?
Steps to reproduce:
1. Upload a file with non-Latin letters in the name, for example: `тест.png`
2. Try to use {file.originalName}

Expected: `тест.png`
Actual: `ÑÐµÑÑ.png`

Checked the database, it gets saved with the wrong encoding there.

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

_No response_

### Zipline Logs

_No response_

### Browser Logs

_No response_

### Additional Info

_No response_

### LINKED ISSUE #318: Bug: can't remove administrator from user
### What happened?

After giving a user admin you cant take it away, when clicking on the user options the administrator slider will appear off.

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

_No response_

### Browser Logs

_No response_

### Additional Info

image

### PR DESCRIPTION
**Pull request by TacticalTechJay**
This PR should fix #318 and fix #317.

Along with that, it adds the following:
  - approriate url for both webhooks where applicable
  - meta tags and audio preview for audio files. They can't be embedded in discord.
  - compression (`content-encoding` header) for the raw route, can be applied to the dashboard where files could be previewed.
  - `CORE_COMPRESSION_ENABLED`, `CORE_COMPRESSION_THRESHOLD`, and `CORE_COMPRESSION_ON_DASHBOARD` variables. this will be disabled by default, Their types are `boolean`, `human-to-byte`, and `boolean`. on_dashboard will have compressed file previews being served on the dashboard
  - some npm errors with `npm i`
  - images resized and fitted to the preview card that's visible both on `/dashboard` and `/files`
  - non-previewables having a centered height on said preview card (or what is close to center)

### CODE REVIEW

File: src/server/decorators/rawFile.ts [hunk 1]
```diff
@@ -2,26 +2,65 @@ import { FastifyInstance, FastifyReply } from 'fastify';
...
   async function rawFile(this: FastifyReply, id: string) {
-    const { download } = this.request.query as { download?: string };
+    const { download, nocompress } = this.request.query as { download?: string; nocompress?: boolean };
 
     const data = await this.server.datasource.get(id);
     if (!data) return this.notFound();
 
     const mimetype = await guess(extname(id).slice(1));
     const size = await this.server.datasource.size(id);
+    this.header('Content-Type', download ? 'application/octt-stream' : mimetype);
```
Comment (diced) [inline src/server/decorators/rawFile.ts]:
```suggestion
    this.header('Content-Type', download ? 'application/octet-stream' : mimetype);
```

**Review by diced — CHANGES_REQUESTED** [review]

**Review by diced — APPROVED** [review]
