### PR TITLE
Sprinkled fixes

### LINKED ISSUE #397: Bug: 500 Error on updating from an older version to 3.7.0
### What happened?

I was updating from 3.5.x -> 3.7.0. I followed the instructions for running from source, and got a 500 error on deploying the website.
The error in the logs at this point:
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useEffect')
    at Module.useEffect (/home/justin/zipline/node_modules/react/cjs/react.development.js:1634:21)
    at QueryClientProvider (file:///home/justin/zipline/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:46:9)
    at renderWithHooks (/home/justin/zipline/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8674:16)
    at renderIndeterminateComponent (/home/justin/zipline/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8748:15)
    at renderElement (/home/justin/zipline/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8983:7)
    at renderNodeDestructiveImpl (/home/justin/zipline/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/home/justin/zipline/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderNode (/home/justin/zipline/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9328:12)
    at renderChildrenArray (/home/justin/zipline/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9277:7)
    at renderNodeDestructiveImpl (/home/justin/zipline/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:7)
```
It was suggested that I use yarn instead, so I deleted the node_modules folder and did an install + build with yarn, and then got a different error:

```
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
    at title
    at head
    at Head (/home/justin/zipline/.next/server/chunks/56859.js:291:1)
    at html
    at Html (/home/justin/zipline/.next/server/chunks/56859.js:685:104)
    at MyDocument (/home/justin/zipline/.next/server/pages/_document.js:30:1)
```

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
    at title
    at head
    at Head (/home/justin/zipline/.next/server/chunks/56859.js:291:1)
    at html
    at Html (/home/justin/zipline/.next/server/chunks/56859.js:685:104)
    at MyDocument (/home/justin/zipline/.next/server/pages/_document.js:30:1)
```

### Browser Logs

```shell
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
    at title
    at head
    at Head (/home/justin/zipline/.next/server/chunks/56859.js:291:1)
    at html
    at Html (/home/justin/zipline/.next/server/chunks/56859.js:685:104)
    at MyDocument (/home/justin/zipline/.next/server/pages/_document.js:30:1)
```

###  Additional Info
N/A  

Edit: diced said on discord the "title" error can be ignored, so this probably has something to do with the React hook calls?

### PR DESCRIPTION
**Pull request by TacticalTechJay**
I've changed the compose file(s) to start using relative path rather than the $PWD variable. The rest of the commits should fix #397. The cause of this was due ot a previous PR that didn't check whether a config was null/undefined or not. The error page will now have a button to refresh if the error happened at `/dashboard`.

### CODE REVIEW

File: src/lib/middleware/getServerSideProps.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ export const getServerSideProps: GetServerSideProps<ServerSideProps> = async (ct
       user_registration: config.features.user_registration,
       oauth_registration: config.features.oauth_registration,
       oauth_providers: JSON.stringify(oauth_providers),
-      bypass_local_login: config.oauth.bypass_local_login,
+      bypass_local_login: config.oauth?.bypass_local_login ?? false,
```
Comment (diced) [inline src/lib/middleware/getServerSideProps.ts:64]: Shouldn't the `config.oauth.bypass_local_login` have a default value within the config?

Comment (TacticalTechJay) [reply src/lib/middleware/getServerSideProps.ts:64]: When no oauth configs are set, it's null.

Comment (TacticalTechJay) [reply src/lib/middleware/getServerSideProps.ts:64]: However if at least one oauth config is present, then the defaults for the others will apply.

**Review by diced — APPROVED** [review]
